all: dodawanieWielkieLiczby odejmowanieWielkieLiczby mnozenieWielkieLiczby

dodawanieWielkieLiczby.o: dodawanieWielkieLiczby.s
	as -g -o dodawanieWielkieLiczby.o dodawanieWielkieLiczby.s

dodawanieWielkieLiczby: dodawanieWielkieLiczby.o
	ld -g -o dodawanieWielkieLiczby dodawanieWielkieLiczby.o

odejmowanieWielkieLiczby.o: odejmowanieWielkieLiczby.s
	as -g -o odejmowanieWielkieLiczby.o odejmowanieWielkieLiczby.s

odejmowanieWielkieLiczby: odejmowanieWielkieLiczby.o
	ld -g -o odejmowanieWielkieLiczby odejmowanieWielkieLiczby.o

mnozenieWielkieLiczby.o: mnozenieWielkieLiczby.s
	as -g -o mnozenieWielkieLiczby.o mnozenieWielkieLiczby.s

mnozenieWielkieLiczby: mnozenieWielkieLiczby.o
	ld -g -o mnozenieWielkieLiczby mnozenieWielkieLiczby.o


